version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Assign pull requests to their creators
    assignees:
      - "hydai"
    # Group all dependencies into a single pull request
    groups:
      dependencies:
        patterns:
          - "*"
    # Add labels to pull requests
    labels:
      - "npm dependencies"
      - "dependabot"
    # Specify the version update strategy
    versioning-strategy: auto

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Add labels to pull requests
    labels:
      - "github-actions"
      - "dependencies"
      - "dependabot"
    # Assign pull requests to their creators
    assignees:
      - "hydai"
